# Generated by Django 4.2.2 on 2023-06-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_profile_profileimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='media/profile_images/default-img.png', upload_to='profile_images'),
        ),
    ]
