# Generated by Django 4.2.2 on 2023-07-04 09:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0673a417-e1e1-4c38-b256-d95d9e536f64'), primary_key=True, serialize=False),
        ),
    ]
