# Generated by Django 4.2.2 on 2023-07-05 09:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('45f8e0eb-26d2-4415-aae9-cc33f09b0480'), primary_key=True, serialize=False),
        ),
    ]
