# Generated by Django 4.2.2 on 2023-07-10 13:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_likepost_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0db84374-5fb3-452f-ac4a-df4cad82b1f2'), primary_key=True, serialize=False),
        ),
    ]
