# Generated by Django 4.2.2 on 2023-07-10 16:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('873ed37b-ba99-440b-8fc9-a841256ecb56'), primary_key=True, serialize=False),
        ),
    ]
