# Generated by Django 4.2.2 on 2023-07-10 17:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4b707d0f-5d4e-4ad0-99fb-05a8418f14b3'), primary_key=True, serialize=False),
        ),
    ]
