# Generated by Django 4.2.2 on 2023-07-13 15:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_followerscount_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9f625d86-8343-4911-9fa1-607efc334a16'), primary_key=True, serialize=False),
        ),
    ]
